# Generated by Django 4.0.4 on 2022-06-24 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0003_convites'),
    ]

    operations = [
        migrations.AddField(
            model_name='convites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='convites',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='convites',
            name='solicitante',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convite', to=settings.AUTH_USER_MODEL),
        ),
    ]
