# Generated by Django 4.0.4 on 2022-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0004_convites_created_at_remove_convites_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convites',
            name='solicitante_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convites',
            name='solicitante',
            field=models.CharField(max_length=150),
        ),
    ]
