# Generated by Django 4.0.4 on 2022-06-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0005_convites_solicitante_id_alter_convites_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='existe_convite',
            field=models.BooleanField(default=False),
        ),
    ]
