# Generated by Django 4.0.4 on 2022-07-02 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0006_profile_existe_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='existe_mensagem',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_id', models.IntegerField()),
                ('origem_nome', models.CharField(max_length=150)),
                ('texto', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destino_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
