# Generated by Django 4.0.4 on 2022-07-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0007_profile_existe_mensagem_mensagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagens',
            name='msg_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mensagens',
            name='sequencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensagens',
            name='status_msg',
            field=models.IntegerField(default=0),
        ),
    ]
