# Generated by Django 4.0.4 on 2022-07-09 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0009_profile_sequencia_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleMsgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_id', models.IntegerField()),
                ('origem_nome', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
