# Generated by Django 4.0.4 on 2022-07-11 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0010_controlemsgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlemsgs',
            name='exibida_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
